"""Changed the VhsRental model: date_returned nullable=True

Revision ID: 937dbf9bc051
Revises: 
Create Date: 2023-02-20 22:17:03.930678

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '937dbf9bc051'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.alter_column('first_name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('last_name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=25),
               existing_nullable=False)

    with op.batch_alter_table('vhs_rental', schema=None) as batch_op:
        batch_op.alter_column('date_returned',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.create_foreign_key(None, 'vhs_details', ['vhs_details_id'], ['id'])
        batch_op.create_foreign_key(None, 'customer', ['customer_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vhs_rental', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('date_returned',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)

    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.String(length=25),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.alter_column('last_name',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.alter_column('first_name',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)

    # ### end Alembic commands ###
